### ISSUE TITLE
api/charge returns 'not found'

### ISSUE THREAD

**Issue by markwj** [openvehicles/Open-Vehicle-Server#11]
User reports:

curl --location --request GET 'https://api.openvehicles.com:6869/api/charge/<VEHICLE>?username=<USER>&password=<PASS>'

returns 'Not found'.

**Comment by sdarveau** [comment]
Also fixed by https://github.com/openvehicles/Open-Vehicle-Server/pull/10

**Comment by markwj** [comment]
Resolved in 3.0.001-16-gd98deef.
