### ISSUE TITLE
Log-in Simple Client

### ISSUE THREAD

**Issue by ThS-Twizy** [openvehicles/Open-Vehicle-Server#14]
I can log on to the server https://ovms.dexters-web.de/ with my access data without any problems and view the vehicles.
When I log in on https://ovms.dexters-web.de/f/simpleclient.htm with the same access data, I always get the response: Authentication failed.

**Comment by dexterbg** [comment]
ThS, according to your report on the german Twizy forum, you're using special characters (german umlauts) in your login and/or password. Can you please add some detail on this:
- which special characters do you use in your credentials?
- do you use them in the login, password, both?
- do you combine multiple special characters?
- do they have special positioning, i.e. at the front or back?
- did you try changing them into ASCII characters? did that solve the issue?

**Comment by ThS-Twizy** [comment]
Hello Dexter,
jes, i have "ä" in the Login-Name and a "!" in the passwort.
I had tried it with my e-mailadress and the pass 123456!, 
The Account will be going with the new credentials, the simple-client not.

**Comment by dexterbg** [comment]
Fixed by commit 62d804cadad1aa1cd97d17930245b13d4ba47f4f
