### ISSUE TITLE
Confusing HTTP status codes

### ISSUE THREAD

**Issue by jabelone** [openvehicles/Open-Vehicle-Server#19]
Hi there!

I've been playing around with the API in order to make an integration with Home Assistant so I can automate charging my Nissan LEAF. I've been playing around and noticed that there's a few confusing HTTP status codes. I've attempted to change them in the linked PR: https://github.com/openvehicles/Open-Vehicle-Server/pull/18

I'm also getting a `404 Not yet implemented` response when I attempt to make a request against `GET http://api.openvehicles.com:6868/api/vehicle/<id>`. However the documentation [here](https://docs.openvehicles.com/en/latest/protocol_httpapi/requests.html#get-api-vehicle-vehicleid) suggests it should be a valid endpoint. Can you please confirm if I'm using it correctly or if there's a bug somewhere?

**Comment by dexterbg** [comment]
Hi Jaimyn,

thanks for the status code corrections, although you could have left some status messages unchanged. But status messages have been obsoleted by http/2 anyway, so nevermind.

`/api/vehicle/<id>` is a new feature not yet available on `api.openvehicles.com`. See http://lists.openvehicles.com/pipermail/ovmsdev/2021-May/015335.html and https://github.com/openvehicles/Open-Vehicle-Server/commit/2d9c36a6cd6c2a78ed9a42724285c5af3095ddb1

Regards,
Michael
