### ISSUE TITLE
Typo: 955=DMC FW: Line Sunc Loss fault

### ISSUE THREAD

**Issue by StuartCheshire** [openvehicles/Open-Vehicle-Server#8]
Is this correct? Should it say, “Line Sync Loss fault”?

**Comment by slcasner** [comment]
On Wed, 4 Mar 2020, Stuart Cheshire wrote:

> Is this correct? Should it say, "Line Sync Loss fault"?

Yes, this is one of a long list of typos and additions that I gave to
Mark a while back.  He said he has incorporated them in the server...

                                                        -- Steve

**Comment by markwj** [comment]
I've reviewed these messages, and revised where necessary. It seems some from Steve's list were missing, so I added them.
